stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
  only:
    - master
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"

# deploy:
#   stage: deploy
#   variables:
#     APP_NAME: "indico-transifex-mirror"
#     NAMESPACE: "indico-transifex-mirror"
#     OPENSHIFT_SERVER: https://api.paas.okd.cern.ch
#   image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
#   only:
#     - master
#   script:
#     # Adding || true to disable the error message when the image already exists
#     - oc import-image ${APP_NAME} --from="${CI_REGISTRY_IMAGE}:latest" --confirm --token=${DEPLOY_TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE} || true
#     - oc tag "${CI_REGISTRY_IMAGE}:latest" "${APP_NAME}:latest" --token=${DEPLOY_TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}

