stages:
  - build
  - deploy

# https://gitlab.cern.ch/gitlabci-examples/build_docker_image
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
  only:
    - master
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"

# https://paas.docs.cern.ch/2._Deploy_Applications/Deploy_Docker_Image/2-automatic-redeployments/#integrate-redeployment-in-ci-workflow
deploy:
  stage: deploy
  variables:
    APP_NAME: "test-indico-transifex-mirror"
    NAMESPACE: "test-indico-transifex-mirror"
    OPENSHIFT_SERVER: https://api.paas.okd.cern.ch
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  only:
    - master
  variables:
    SERVER: https://api.paas.okd.cern.ch
    PROJECT: test-indico-transifex-mirror
    APP_NAME: indico-transifex-mirror
  script:
    - oc login $SERVER --token=$DEPLOY_TOKEN
    - oc project $PROJECT
    - oc import-image $APP_NAME --all
    - sleep 10 && oc rollout status deployment/$APP_NAME
